services:
  postgres:
    image: postgres:16
    container_name: nest_users_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest_user
      POSTGRES_PASSWORD: nest_password
      POSTGRES_DB: nest_users_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: